import os
import sys
import shlex
import subprocess
import json
from pydantic import BaseModel, Field
from google import genai
from dotenv import load_dotenv

load_dotenv()

# Use provided config environment variables
# Usually GEMINI_API_KEY is used by the client automatically if initialized without args.

class CommandOutput(BaseModel):
    primary_command: str = Field(description="Primary gh command, usually gh issue list, using --json number,title,url")
    fallback_command: str = Field(description="Fallback gh command, usually gh pr list, using --json number,title,url")

def get_gemini_client():
    return genai.Client()

def generate_gh_commands(repo: str, idea: str) -> CommandOutput:
    """Uses Gemini API to interpret the idea and generate structured gh commands."""
    try:
        client = get_gemini_client()
    except Exception as e:
        raise RuntimeError("Could not initialize Gemini Client. Ensure GEMINI_API_KEY is set in your environment.") from e

    prompt = f"""
You are an expert GitHub CLI (gh) command generator.
The user wants to find contribution opportunities in an open source GitHub repository based on their idea.

Given the repository "{repo}" and the user's idea: "{idea}"

Generate the best `gh` commands to search for relevant issues, and a fallback to search for relevant pull requests.
Constraints for the commands:
1. Must be read-only search commands (`gh issue list` or `gh pr list`).
2. Must use `--repo {repo}`
3. Must use `--limit 5`
4. Must use `--state open`
5. Must include appropriate `--search "..."` or `--label "..."` based on the idea.
6. MUST include `--json number,title,url` at the end of the command to ensure the output can be parsed by our execution engine.

Only generate the two commands in the structured JSON output. Do NOT add markdown blocks or code formatting around JSON, return strictly JSON.
"""

    # Based on the documentation, supported models include gemini-3-flash-preview
    # and gemini-2.5-flash-lite. We'll use gemini-3-flash-preview.
    model_name = "gemini-3-flash-preview"
    
    config = {
        "response_mime_type": "application/json",
        "response_json_schema": CommandOutput.model_json_schema(),
        "temperature": 0.2, # low temperature for deterministic CLI outputs
    }

    try:
        response = client.models.generate_content(
            model=model_name,
            contents=prompt,
            config=config,
        )
    except Exception as e:
        # If gemini-3-flash-lite isn't formally available in the SDK yet, fallback to a known model format
        print(f"Fallback model used due to: {e}")
        response = client.models.generate_content(
            model="gemini-2.5-flash-lite", 
            contents=prompt,
            config=config,
        )

    return CommandOutput.model_validate_json(response.text)

def validate_command(cmd: str) -> bool:
    """Basic validation to prevent arbitrary shell execution."""
    cmd = cmd.strip()
    if not cmd.startswith("gh "):
        return False
    # Allowed prefixes
    allowed = ["gh issue list", "gh pr list", "gh search issues", "gh search prs"]
    if not any(cmd.startswith(a) for a in allowed):
        return False
    # Forbid multi command expressions
    forbidden_chars = [";", "&&", "||", "|", ">", "<", "$", "`"]
    if any(char in cmd for char in forbidden_chars):
        return False
    return True

def execute_gh_command(cmd_str: str) -> list:
    """Executes a gh command and parses its JSON output."""
    if not validate_command(cmd_str):
        raise ValueError(f"Invalid or unsafe command generated by AI: {cmd_str}")

    # Use shlex to safely break up the command string into a sequence of arguments.
    # This ensures we don't accidentally do shell injection.
    # POSIX parameter handles quotes properly on Windows Python typically, but Windows shlex can be tricky.
    args = shlex.split(cmd_str, posix=True)
    
    try:
        # shell=False prevents arbitrary shell operators from engaging.
        result = subprocess.run(args, capture_output=True, text=True, check=True, shell=False)
        output = result.stdout.strip()
        if output:
            try:
                return json.loads(output)
            except json.JSONDecodeError:
                return []
        return []
    except subprocess.CalledProcessError as e:
        print(f"Command execution error: {e.stderr}", file=sys.stderr)
        return []
    except FileNotFoundError:
        print("Error: GitHub CLI (gh) not found. Please install it.", file=sys.stderr)
        sys.exit(1)

def search_contributions(repo: str, idea: str):
    """Orchestrates the fallback logic"""
    try:
        commands = generate_gh_commands(repo, idea)
    except Exception as e:
        return {"error": f"Failed to generate commands from Gemini: {e}"}

    primary = commands.primary_command
    fallback = commands.fallback_command

    results = execute_gh_command(primary)
    if results:
        return {"type": "issues", "data": results, "command": primary}
    
    results = execute_gh_command(fallback)
    if results:
        return {"type": "pull requests", "data": results, "command": fallback}
    
    return {"type": "none", "data": [], "command": None}
